use_frameworks!

source 'https://github.com/YeebZ/MyPodTest'
source 'https://github.com/CocoaPods/Specs.git'

target 'Pod_lib_test_Example' do
  pod 'Pod_lib_test', :path => '../'

  target 'Pod_lib_test_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
